### ISSUE TITLE
Bower install error

### ISSUE THREAD

**Issue by ghost** [johnpozy/flot-spline#2]
Hi,

I get the following error when I try to install the package using bower:
bower ENORESTARGET  No tag found that was able to satisfy ~0.0.1
No versions found in git://github.com/JohnPozy/flot-spline.git

Thanks for your help

**Comment by bbooth** [comment]
I think all that needs to happen is to create the git tag 0.0.1.  Maybe @JohnPozy can do that quick.  Else you might want try pointing your bower just to the repo master.

**Comment by johnpozy** [comment]
done...
