### ISSUE TITLE
Please tag versions correctly

### ISSUE THREAD

**Issue by beruic** [johnpozy/flot-spline#4]
The current version tag [0.0.1](https://github.com/johnpozy/flot-spline/tree/0.0.1) contains the script version [0.8.2](https://github.com/johnpozy/flot-spline/blob/0.0.1/js/jquery.flot.spline.js).

Correct version tags makges it easy to refer to a release by using [RawGit](https://rawgit.com/). Currently supplying RawGit with [https://github.com/johnpozy/flot-spline/blob/0.0.1/js/jquery.flot.spline.js](https://github.com/johnpozy/flot-spline/blob/0.0.1/js/jquery.flot.spline.js) gives you [https://cdn.rawgit.com/johnpozy/flot-spline/0.0.1/js/jquery.flot.spline.js](https://cdn.rawgit.com/johnpozy/flot-spline/0.0.1/js/jquery.flot.spline.js), which is actually version `0.8.2`.

**Comment by johnpozy** [comment]
https://github.com/johnpozy/flot-spline/releases/tag/0.8.2

**Comment by beruic** [comment]
I have no idea why that was not showing to me before. Thanks. Sorry for the inconvenience.
